server:
  port: 8078
  
spring:
#  datasource:
#    url: jdbc:mysql://<host>:<port>/<dbname>
#    username: <username>
#    password: <password>
  jpa:
    hibernate:
      ddl-auto: create-drop # 운영시에는 validate 추천
    show-sql: true
    
  devtools:    livereload:      enabled: true